---

# Configure Linux
- name: RedHat | Install required packages
  yum: name={{ item }} state=present
  with_items: rh.packages_depends

- name: Disable SELinux
  selinux: state=disabled

# Create users and groups
- name: Create oracle group
  group: name={{ oracle_system_group }} state=present

- name: Add oracle extra groups
  group: name={{ item }} state=present
  with_items: oracle_extra_groups

- name: Create oracle user
  user: name={{ oracle_system_user }} group={{ oracle_system_group }} password={{ oracle_system_user_password }}

- name: Create Oracle Base directory
  file: state=directory path={{ oracle_base_dir }} owner={{ oracle_system_user }} group={{ oracle_system_group }}

- name: Add oracle extra groups
  user: name={{ oracle_system_user }} groups={{ item }} append=yes
  with_items: oracle_extra_groups

- name: Add oracle user limits
  lineinfile: dest=/etc/security/limits.conf line="{{ oracle_system_user }} {{ item.limit }} {{ item.type}} {{ item.value }}"
  with_items: sys_config.limits

# Disable transparent hugepages
- name: Copy script to disable transparent hugepages
  copy: src=disable_trans_hugepages.sh dest='/tmp/disable_trans_hugepages.sh' mode=755

- name: Disable Transparent Huge Pages
  shell: '/tmp/disable_trans_hugepages.sh'

- name: Remove the script
  file: path='/tmp/disable_trans_hugepages.sh' state=absent

- name: Configure kernel for hugepages
  sysctl: name='vm.nr_hugepages' value="{{ sys_config.hugepages_nr }}" state=present
